#use_frameworks!

#platform :ios, '9.0'

target 'FFLimitTextView_Example' do
  pod 'FFLimitTextView', :path => '../'
  
  pod 'FFCategories', '~> 0.0.1'

  target 'FFLimitTextView_Tests' do
    inherit! :search_paths

    
  end
end
